use_frameworks!

platform :ios, '9.0'

target 'Details_Example' do
  pod 'Details', :git => 'https://github.com/elisa-c/Details'

  target 'Details_Tests' do
    inherit! :search_paths

    
  end
end
